### ISSUE TITLE
How do I get a public gist?

### ISSUE THREAD

**Issue by boba-and-beer** [fastai/ghapi#34]
How do I get a public gist? 

I was interested in retrieving a public gist in Github. 

Example: 
Given the following gist: 
```
- url: https://api.github.com/gists/abcc6208af09ddaff6725b87b05be034
- forks_url: https://api.github.com/gists/abcc6208af09ddaff6725b87b05be034/forks
- commits_url: https://api.github.com/gists/abcc6208af09ddaff6725b87b05be034/commits
- id: abcc6208af09ddaff6725b87b05be034
- node_id: MDQ6R2lzdGFiY2M2MjA4YWYwOWRkYWZmNjcyNWI4N2IwNWJlMDM0
- git_pull_url: https://gist.github.com/abcc6208af09ddaff6725b87b05be034.git
- git_push_url: https://gist.github.com/abcc6208af09ddaff6725b87b05be034.git
- html_url: https://gist.github.com/abcc6208af09ddaff6725b87b05be034
- files: 
  - main.py: 
    - filename: main.py
    - type: application/x-python
    - language: Python
    - raw_url: https://gist.githubusercontent.com/daanklijn/abcc6208af09ddaff6725b87b05be034/raw/e69e00be58406d956e2cd22f6c4c83569172db23/main.py
    - size: 680
- public: True
- created_at: 2021-01-11T14:45:30Z
- updated_at: 2021-01-11T14:45:31Z
- description: main
- comments: 0
- user: None
- comments_url: https://api.github.com/gists/abcc6208af09ddaff6725b87b05be034/comments
- owner: 
  - login: daanklijn
  - id: 27863547
  - node_id: MDQ6VXNlcjI3ODYzNTQ3
  - avatar_url: https://avatars0.githubusercontent.com/u/27863547?v=4
  - gravatar_id: 
  - url: https://api.github.com/users/daanklijn
  - html_url: https://github.com/daanklijn
  - followers_url: https://api.github.com/users/daanklijn/followers
  - following_url: https://api.github.com/users/daanklijn/following{/other_user}
  - gists_url: https://api.github.com/users/daanklijn/gists{/gist_id}
  - starred_url: https://api.github.com/users/daanklijn/starred{/owner}{/repo}
  - subscriptions_url: https://api.github.com/users/daanklijn/subscriptions
  - organizations_url: https://api.github.com/users/daanklijn/orgs
  - repos_url: https://api.github.com/users/daanklijn/repos
  - events_url: https://api.github.com/users/daanklijn/events{/privacy}
  - received_events_url: https://api.github.com/users/daanklijn/received_events
  - type: User
  - site_admin: False
- truncated: False
```
I then tried to run the code: 
```
gh_client.gists.get('10199742')
```

However, this returned:

```
*** fastcore.basics.HTTP404NotFoundError: HTTP Error 404: Not Found
```

Is there any way to retrieve a public gist like the one above?

Note: This may not be the right place to make this issue. After reading contributing guidelines, I couldn't find where to point my questions so let me know if there is a better place.
